package qlstudent;
// Generated Aug 15, 2020 10:49:38 PM by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private int masv;
     private String name;
     private int old;
     private String class_;

    public Student() {
    }

    public Student(int masv, String name, int old, String class_) {
       this.masv = masv;
       this.name = name;
       this.old = old;
       this.class_ = class_;
    }
   
    public int getMasv() {
        return this.masv;
    }
    
    public void setMasv(int masv) {
        this.masv = masv;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getOld() {
        return this.old;
    }
    
    public boolean setOld(int old) {
        if(old >= 18&& old <=40){
            this.old = old;
            return true;
        }
        else{
            System.err.println("Nhap sai ! ");
            return false;
        }
        
    }
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }

    @Override
    public String toString() {
        return "Student :" + "masv=" + masv + ", name=" + name + ", old=" + old + ", class=" + class_ + ",";
    }

    


}


